### ISSUE TITLE
Logo design for HMS

### ISSUE THREAD

**Issue by zuurw** [ravinathdo/HMS#1]
Hi , my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by ravinathdo** [comment]
Thank you for the interesting. I'm initial started some basic icons. But if
u can collaborate with much more professional it's really helpful. I'll let
u know the details and. If u could send me ur GitHub username name .I can
add u as a collaborator


Thanks
ravinathdo

**Comment by zuurw** [comment]
Hi @ravinathdo, my user name is @zuurw.
So I would like to know if you have something in your mind for the logo? any special request?

Best Regards!

**Comment by zuurw** [comment]
Hi @ravinathdo, I create 3 designs for your project, with some color variations, see if you like one of this logos, if not I can make other one.

Best regards

![proposal](https://user-images.githubusercontent.com/40801473/44585920-d16faf00-a7a5-11e8-8560-b29b7fcaaf12.png)

**Comment by ravinathdo** [comment]
thanks seams grate. ill apply and share with u how its look like

**Comment by zuurw** [comment]
Hi wich one you like?

**Comment by zuurw** [comment]
Hi @ravinathdo, how are you? I would like to know if you are using one of my designs that I create for HMS.
I would like to send you the PNG and Editable files.

Greetings
